<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-ios17.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>vault.iOS</RootNamespace>
    <AssemblyName>vault.iOS</AssemblyName>

    <ApplicationTitle>Cassaforte iOS</ApplicationTitle>
    <ApplicationId>com.luca07giochi.vaultios</ApplicationId>
    <ApplicationDisplayVersion>1.2.3</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchExtraArgs>$(MtouchExtraArgs) --gcc_flags "-framework Security -framework CoreFoundation"</MtouchExtraArgs>
    <PublishTrimmed>true</PublishTrimmed>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\vault.Core\vault.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <NativeReference Include="/System/Library/Frameworks/Security.framework">
      <Kind>Framework</Kind>
    </NativeReference>
    <NativeReference Include="/System/Library/Frameworks/CoreFoundation.framework">
      <Kind>Framework</Kind>
    </NativeReference>
  </ItemGroup>

</Project>
