<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-ios16.4</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>vault.iOS.Shared</RootNamespace>
    <AssemblyName>vault.iOS.Shared</AssemblyName>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

</Project>
